<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="fbInConveyor" Id="{76ca436e-5ee1-43c3-bba6-80a39f7f3701}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fbInConveyor
VAR_INPUT
	SafetyOk			: BOOL;
	ResetCmd			: BOOL;
	AutoCycle			: BOOL;
	ManualCmd			: BOOL;
	
END_VAR
VAR_OUTPUT
	ResetCompleted 		: BOOL;
	
END_VAR
VAR
	FwdConveyor			AT %Q* :BOOL;
	State						: INT := 0;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="fbInConveyor">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>